version: "3.7"

services:
  api:
    image: api_teste:v1
    ports:
      - "4444:4444"
    networks:
      - api-network
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  api-network:
    driver: overlay
    attachable: true